### ISSUE TITLE
girder: empty items

### ISSUE THREAD

**Issue by yarikoptic** [dandisets/000026#1]
```
DANDI:000026      Empty item with prefix=rawdata/sub-I46/ses-OCT/: {'_id': '602ee37302cb75004f0af67b', '_modelType': 'item', 'baseParentId': '5e59bb0af19e820ab6ea6c62', 'baseParentType': 'collection', 'created': '2021-02-18T22:00:19.531000+00:00', 'creatorId': '5f106a1a18eb78d1fe6511af', 'description': '', 'folderId': '5f15f7f5f63d62e1dbd068d9', 'meta': {}, 'name': 'volume_high_res.mat', 'size': 0, 'updated': '2021-02-18T22:00:19.531000+00:00'}
  Empty item with prefix=sub-I46/microscopy/: {'_id': '607475c002cb75004f0b2b17', '_modelType': 'item', 'baseParentId': '5e59bb0af19e820ab6ea6c62', 'baseParentType': 'collection', 'created': '2021-04-12T16:30:56.265000+00:00', 'creatorId': '5f158b6ef63d62e1dbd068d4', 'description': '', 'folderId': '606d7d0f02cb75004f0b2057', 'meta': {}, 'name': 'sub-I46_sample-MotorCortexS01_stain-Calretinin_chunk-03_SPIM.ome.tiff', 'size': 0, 'updated': '2021-04-12T16:30:56.265000+00:00'}
  Empty item with prefix=sub-I46/microscopy/: {'_id': '6074764f02cb75004f0b2b20', '_modelType': 'item', 'baseParentId': '5e59bb0af19e820ab6ea6c62', 'baseParentType': 'collection', 'created': '2021-04-12T16:33:19.482000+00:00', 'creatorId': '5f158b6ef63d62e1dbd068d4', 'description': '', 'folderId': '606d7d0f02cb75004f0b2057', 'meta': {}, 'name': 'sub-I46_sample-MotorCortexS01_stain-Calretinin_chunk-10_SPIM.ome.tiff', 'size': 0, 'updated': '2021-04-12T16:33:19.482000+00:00'}
  Empty item with prefix=sub-I46/microscopy/: {'_id': '607476f102cb75004f0b2b26', '_modelType': 'item', 'baseParentId': '5e59bb0af19e820ab6ea6c62', 'baseParentType': 'collection', 'created': '2021-04-12T16:36:01.638000+00:00', 'creatorId': '5f158b6ef63d62e1dbd068d4', 'description': '', 'folderId': '606d7d0f02cb75004f0b2057', 'meta': {}, 'name': 'sub-I46_sample-MotorCortexS03_stain-Calretinin_chunk-04_SPIM.ome.tiff', 'size': 0, 'updated': '2021-04-12T16:36:01.638000+00:00'}
  Empty item with prefix=sub-I46/microscopy/: {'_id': '6074780e02cb75004f0b2b29', '_modelType': 'item', 'baseParentId': '5e59bb0af19e820ab6ea6c62', 'baseParentType': 'collection', 'created': '2021-04-12T16:40:46.977000+00:00', 'creatorId': '5f158b6ef63d62e1dbd068d4', 'description': '', 'folderId': '606d7d0f02cb75004f0b2057', 'meta': {}, 'name': 'sub-I46_sample-MotorCortexS03_stain-Calretinin_chunk-08_SPIM.ome.tiff', 'size': 0, 'updated': '2021-04-12T16:40:46.977000+00:00'}
  Empty item with prefix=sub-I46/microscopy/: {'_id': '60747a8b02cb75004f0b2b31', '_modelType': 'item', 'baseParentId': '5e59bb0af19e820ab6ea6c62', 'baseParentType': 'collection', 'created': '2021-04-12T16:51:23.575000+00:00', 'creatorId': '5f158b6ef63d62e1dbd068d4', 'description': '', 'folderId': '606d7d0f02cb75004f0b2057', 'meta': {}, 'name': 'sub-I46_sample-MotorCortexS03_stain-NeuN_chunk-00_SPIM.ome.tiff', 'size': 0, 'updated': '2021-04-12T16:51:23.575000+00:00'}
  Empty item with prefix=sub-I46/microscopy/: {'_id': '60747c0102cb75004f0b2b35', '_modelType': 'item', 'baseParentId': '5e59bb0af19e820ab6ea6c62', 'baseParentType': 'collection', 'created': '2021-04-12T16:57:37.964000+00:00', 'creatorId': '5f158b6ef63d62e1dbd068d4', 'description': '', 'folderId': '606d7d0f02cb75004f0b2057', 'meta': {}, 'name': 'sub-I46_sample-MotorCortexS03_stain-NeuN_chunk-10_SPIM.ome.tiff', 'size': 0, 'updated': '2021-04-12T16:57:37.964000+00:00'}
  Empty item with prefix=sub-I46/microscopy/: {'_id': '60747a6602cb75004f0b2b2c', '_modelType': 'item', 'baseParentId': '5e59bb0af19e820ab6ea6c62', 'baseParentType': 'collection', 'created': '2021-04-12T16:50:46.835000+00:00', 'creatorId': '5f158b6ef63d62e1dbd068d4', 'description': '', 'folderId': '606d7d0f02cb75004f0b2057', 'meta': {}, 'name': 'sub-I46_sample-MotorCortexS03_stain-Nuclei_chunk-00_SPIM.ome.tiff', 'size': 0, 'updated': '2021-04-12T16:50:46.835000+00:00'}
  Empty item with prefix=sub-I46/microscopy/: {'_id': '60747a8b02cb75004f0b2b30', '_modelType': 'item', 'baseParentId': '5e59bb0af19e820ab6ea6c62', 'baseParentType': 'collection', 'created': '2021-04-12T16:51:23.142000+00:00', 'creatorId': '5f158b6ef63d62e1dbd068d4', 'description': '', 'folderId': '606d7d0f02cb75004f0b2057', 'meta': {}, 'name': 'sub-I46_sample-MotorCortexS03_stain-Nuclei_chunk-05_SPIM.ome.tiff', 'size': 0, 'updated': '2021-04-12T16:51:23.142000+00:00'}
  Empty item with prefix=sub-I46/microscopy/: {'_id': '60747c7d02cb75004f0b2b38', '_modelType': 'item', 'baseParentId': '5e59bb0af19e820ab6ea6c62', 'baseParentType': 'collection', 'created': '2021-04-12T16:59:41.590000+00:00', 'creatorId': '5f158b6ef63d62e1dbd068d4', 'description': '', 'folderId': '606d7d0f02cb75004f0b2057', 'meta': {}, 'name': 'sub-I46_sample-MotorCortexS04_stain-Calretinin_chunk-01_SPIM.ome.tiff', 'size': 0, 'updated': '2021-04-12T16:59:41.590000+00:00'}
  Empty item with prefix=sub-I46/microscopy/: {'_id': '60747c8a02cb75004f0b2b3b', '_modelType': 'item', 'baseParentId': '5e59bb0af19e820ab6ea6c62', 'baseParentType': 'collection', 'created': '2021-04-12T16:59:54.535000+00:00', 'creatorId': '5f158b6ef63d62e1dbd068d4', 'description': '', 'folderId': '606d7d0f02cb75004f0b2057', 'meta': {}, 'name': 'sub-I46_sample-MotorCortexS04_stain-Calretinin_chunk-10_SPIM.ome.tiff', 'size': 0, 'updated': '2021-04-12T16:59:54.535000+00:00'}
1196 assets the same
```

ref: https://github.com/dandi/dandi-cli/pull/589

**Comment by satra** [comment]
@gmazzamuto - there were a few files that did not make it to the previous server. we detected the ones above. you may want to update the files using the new CLI + API server. and let us know when they are in place.

**Comment by gmazzamuto** [comment]
Hi all,

I have re-uploaded those files. Can you please double-check that everything is fine? I got a `Error 403 while sending POST request to https..` for each of those files but I think the upload went through. If everything is ok, then I'll proceed to move the SPIM data to the rawdata folder.

Thanks
Giacomo

**Comment by satra** [comment]
@gmazzamuto - do you have the information about the error - it is probably in the log files. 

i would worry about any error at this point :)  cc:ing @yarikoptic as well.

now  that we have an api server, you can also check if the files are there by doing this.

> curl -X GET "https://api.dandiarchive.org/api/dandisets/000026/versions/draft/assets/paths/?path_prefix=sub-I46%2Fmicroscopy" -H  "accept: application/json"

**Comment by yarikoptic** [comment]
yeah -- errors are not nice.  me not liking errors too. Indeed there should be a log file (path usually announced by dandi-cli on each run) -- may be you could find the one (with a simple `grep "403 while" ~/.cache/dandi-cli/log/* ` if on linux; or by date/time)  and share if it looks like having relevant information/tracebacks etc? (I do not think it should have any sensitive info but please check)

**Comment by gmazzamuto** [comment]
Indeed the files are not there.. it seems the upload didn't work in the end. I'm attaching the full log here.
[20210427105429Z-3424487.log](https://github.com/dandisets/000026/files/6387158/20210427105429Z-3424487.log)

**Comment by satra** [comment]
@gmazzamuto - could you please paste the command you used? did it include ignoring validation?

**Comment by yarikoptic** [comment]
I assume it did since then it would have not even tried to upload. 403 is permissions issue... unfortunately we do not log more than that on client side OR on server side seems to me -- in papertrail I see only  `[27/Apr/2021:11:05:11 +0000] "POST /api/dandisets/000026/versions/draft/assets/ HTTP/1.1" 403 0 "-" "dandi/0.14.2 requests/2.25.1 CPython/3.8.5"` . 

@dchiquito - upon 403 is there more details provided to the user (not owner etc) in the message somewhere so we could pass it to the user?

**Comment by gmazzamuto** [comment]
@satra Yes... that's the command I've always used:
```
DANDI_DEVEL=1 dandi upload --allow-any-path --validation ignore sub-I46/microscopy/sub-I46_sample-MotorCortexS01_stain-Calretinin_chunk-10_SPIM.ome.tiff
```

**Comment by yarikoptic** [comment]
Would you be so kind to try
```
DANDI_DEVEL=1 dandi -l 1 upload --allow-any-path --validation skip sub-I46/microscopy/sub-I46_sample-MotorCortexS01_stain-Calretinin_chunk-10_SPIM.ome.tiff
```
and share the log (again -- if nothing sensitive in there)

**Comment by gmazzamuto** [comment]
Here it is (I passed all the 10 files to be uploaded as argument)
[20210427200523Z-3536710.log](https://github.com/dandisets/000026/files/6387343/20210427200523Z-3536710.log)

**Comment by satra** [comment]
@gmazzamuto - a couple of quick checks: 
- if you click on My dandisets do you see dataset 26? 
- did you get a new API token after you logged in?

**Comment by gmazzamuto** [comment]
- No: it says You haven't created any dandisets yet 
- Yes, I did get a new API token

**Comment by satra** [comment]
@gmazzamuto - that's the issue - let us fix the association.

**Comment by satra** [comment]
@gmazzamuto - you can check my dandisets again. and then if 26 shows up, try the upload !

**Comment by gmazzamuto** [comment]
The upload only took 10s, which I think it means that the files were cached somewhere on your servers after my previous upload. Now they show up in the file list, can you please check their file size?

**Comment by satra** [comment]
Yes. That makes sense. The API key allowed you to upload the files, but not associate them with your dandiset because your ownership was not set. I'll send some simple code to download the asset manifest.

**Comment by satra** [comment]
@gmazzamuto here is a python code snippet that should return all the items. 

```python
import requests
url = "https://api.dandiarchive.org/api/dandisets/000026/versions/draft/assets/"
querystring = {"path":"sub-I46/microscopy","page_size":"100"}
headers = {"Accept": "application/json"}
resp = requests.request("GET", url, headers=headers, params=querystring).json()
results = resp["results"]
while resp["next"]:
    resp = requests.request("GET", resp["next"], headers=headers).json()
    results.extend(resp["results"])
assert len(results) == resp["count"]
```

results will contain all the paths. you can then use pandas to quickly view the ones you uploaded. i'm showing 11 to just show that you had 10 uploads.

```python
import pandas as pd
df = pd.DataFrame(results)
df.sort_values("modified", ascending=False)[["path", "size", "modified"]].iloc[:11].values
```

also i noticed that these new files were distinctly different in size from previous files. could you please make sure that is correct.

**Comment by gmazzamuto** [comment]
I checked using this code, and I discovered that another 10 files or so from the Motor Cortex didn't make it to the server. I uploaded the missing files, and now the byte size of the whole dataset on DANDI sums up exactly to the dataset size on our server. Everything looks good now. I can proceed to move the folder to rawdata then. Thank you!

**Comment by satra** [comment]
thanks @gmazzamuto - i'm going to close this issue as resolved. feel free to reach out via posting an issue or discussion on the https://github.com/dandi/helpdesk repo.

regarding the move. to be compliant with bids, make sure to put the data in a  `ses-SPIM` folder for the participant and include `ses-SPIM` in the filename. after a local renaming the actual upload process again should run very fast since the actual data is already on the server.
