### ISSUE TITLE
Files under `sub-I46/ses-SPIM`need a datatype subdirectory, presumably `sub-I46/ses-SPIM/micr`

### ISSUE THREAD

**Issue by TheChymera** [dandisets/000026#3]
Datatype files should not be directly under the session subdirectory.

@gmazzamuto this is to split off the discussion from the other thread which was getting cluttered.

**Comment by gmazzamuto** [comment]
Hi, can you please let us know when the validator you're working at will be available? So that we can first run it locally before uploading to DANDI.

I am tagging @filippocastelli who will give a hand with fixing our files files in `sub-I46`.

**Comment by yarikoptic** [comment]
you can subscribe-to/monitor https://github.com/dandi/dandi-cli/pull/896 to keep finger on the pulse, unless @TheChymera provides temporary (quicker) workaround meanwhile using already existing code.

**Comment by TheChymera** [comment]
@gmazzamuto @filippocastelli https://github.com/dandi/dandi-cli/pull/896#issuecomment-1029731309

While the output is unambiguous, it might be difficult to read since it just lists unrecognized files and regex expressions — which ofc is all the info needed to debug, but is a bit opaque if you're unfamiliar with regex.
I have tried to report all issues present via the issue tracker here, perhaps the easiest would be to try to fix the files and see if they disappear from the unrecognized files listing after you re-run validation. The logs are saved under unique names and you can `diff` them.

The validator will ofc get even better, but in a pinch it should already suffice :)

**Comment by gmazzamuto** [comment]
Could you please give me some general pointers on how I can make direct API calls to move and rename files? I need to

- rename files from `*.tiff` to `.tif`
- move everything in `micr` subdirectory

I was looking at Swagger but I need some guidance..

thanks!

**Comment by yarikoptic** [comment]
there is no "MOVE" API endpoint.

- ping to https://github.com/dandi/dandi-cli/issues/1006 -- asking for `dandi move` command.  It would have been something you would have used @gmazzamuto right?
- there is no notion of "directory" on S3 and thus also in dandi-api.  Pretty much you just need to traverse all assets and PUT their updated metadata where you set `path` to the value you desire.   @jwodder -- would you be so kind to provide `dandi` library API based version to perform such an action in Python?

**Comment by jwodder** [comment]
@yarikoptic What exactly do you need this code to do?  Just change all `*.tiff` paths to `*.tif` and move ... what? to `sub-I46/ses-SPIM/micr` (?).

**Comment by yarikoptic** [comment]
something like `path.replace(".tiff", ".tif").replace("ses-SPIM/", "ses-SPIM/micr/")` -- @gmazzamuto could adjust to his need/liking.  It should be more of an example following the "best practices" of use of `dandi.dandiapi` to perform file renaming/moving ;)

**Comment by satra** [comment]
this is an adapted snippet from something that i had sent to the allen institute folks. however, it would indeed be nice, if one could do path movements with the asset object itself.

```python
from dandi.dandiapi import DandiAPIClient
from dandischema.models import BioSample, SampleType, Asset
from dandischema import validate

api = DandiAPIClient("https://api.dandiarchive.org/api", token=<TOKEN>)
ds = api.get_dandiset("000026")
for asset in ds.get_assets():  ## hopefully this can be restricted with the new glob feature
    break
meta = asset.get_metadata()
meta.path = <new path>
validate(meta.json_dict(), json_validation=True) # in case you want to check before you update.
asset.set_metadata(meta)
```

**Comment by gmazzamuto** [comment]
That seems to have worked, thanks @satra! The original files still appear to be there though, I guess I can remove them in the usual way.

For reference, this is the code that I have used:

```py
from dandi.dandiapi import DandiAPIClient
from dandischema.models import BioSample, SampleType, Asset
from dandischema import validate

from pathlib import Path

api = DandiAPIClient("https://api.dandiarchive.org/api", token=<TOKEN>)
ds = api.get_dandiset("000026")

for asset in ds.get_assets():
    if not asset.path.startswith('rawdata/sub-I46/ses-SPIM'):
        continue
    oldpath = Path(asset.path)
    newpath = Path('rawdata/sub-I46/ses-SPIM/micr') / oldpath.name
    if newpath.suffix == '.tiff':
        newpath = newpath.with_suffix('.tif')
    meta = asset.get_metadata()
    meta.path = str(newpath)
    validate(meta.json_dict(), json_validation=True)
    asset.set_metadata(meta)
```

> ping to https://github.com/dandi/dandi-cli/issues/1006 -- asking for dandi move command. It would have been something you would have used @gmazzamuto right?

@yarikoptic Yes, that would have been very convenient!

As a side note, I tried to call `validate_bids()` in addition to `validate()` but it didn't work, it seems the function wants real paths rather than strings. For the same reason, `dandi validate-bids` doesn't work with broken git-annex links. I had to `git annex get` a couple of files and then test my changes on them, before running `dandi validate-bids`. But I guess this makes sense, if validate-bids will in the future be able to validate BIDS overall i.e. the file contents, not just paths.

**Comment by satra** [comment]
@gmazzamuto - thanks for the update. 

@jwodder doesn't `set_metadata` use a put request? is there anything in the above code that would suggest why the original asset with path would remain?

**Comment by jwodder** [comment]
@satra

> doesn't set_metadata use a put request?

Yes, it does.

> is there anything in the above code that would suggest why the original asset with path would remain?

No.

**Comment by satra** [comment]
thank you @jwodder . 

@gmazzamuto - perhaps it was a browser cache thing. could you check using the api that you can actually find the old asset? using `ds.get_asset_by_path`

**Comment by gmazzamuto** [comment]
Yes, I am able to call `ds.get_asset_by_path` with the old path. Also, trying with a new browser session in private mode still shows the old assets... doesn't seem to be a browser cache issue.

**Comment by gmazzamuto** [comment]
Can I proceed and delete the old stuff?

**Comment by gmazzamuto** [comment]
I've deleted the old assets, if everything is fine we can close this issue

**Comment by TheChymera** [comment]
@gmazzamuto thanks 💛 seems to have been fixed.
